import React from "react";
import type { Metadata } from "next";
import { FaHome, FaUpload } from "react-icons/fa";
import { MdLibraryBooks } from "react-icons/md";
import NavLink from "@/components/Navlink";

export const metadata: Metadata = {
  title: "Anivie - Dashboard",
  description: "Generated by create next app",
};

const layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className="bg-white text-gray-900">
      <div className="drawer lg:drawer-open">
        <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
        <div className="drawer-content flex flex-col items-center justify-center">
          {children}
          <label
            htmlFor="my-drawer-2"
            className="btn btn-outline drawer-button lg:hidden text-gray-900 border-gray-300"
          >
            Open Menu
          </label>
        </div>
        <div className="drawer-side">
          <label
            htmlFor="my-drawer-2"
            aria-label="close sidebar"
            className="drawer-overlay"
          ></label>
          <ul className="menu p-4 w-80 min-h-full bg-gray-100 border-r border-gray-300 space-y-4">
            <h3 className="text-gray-800 text-3xl text-center font-bold my-6">
              Quiztex
            </h3>

            <li>
              <NavLink
                className="flex items-center gap-4 hover:text-blue-500 hover:bg-neutral p-3 rounded-lg font-medium transition"
                href="/"
                exact
              >
                <FaHome className="text-xl" />
                <span>Home</span>
              </NavLink>
            </li>
            <li>
              <NavLink
                className="flex items-center gap-4 hover:text-blue-500 hover:bg-neutral p-3 rounded-lg font-medium transition"
                href="/admin/questions"
                exact
              >
                <MdLibraryBooks className="text-xl" />
                <span>Questions</span>
              </NavLink>
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default layout;
